/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 84968
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public HomeAdmin() {
        initComponents();

        this.setSize(1366, 768);
        quanlyuser.setIcon(new ImageIcon("Images/quanlyuser.png"));
        quanlyluat.setIcon(new ImageIcon("Images/quanlyluat.png"));
        quanlybienbao.setIcon(new ImageIcon("Images/quanlybienbao.png"));
        quanlybaithi.setIcon(new ImageIcon("Images/quanlybaithi.png"));
        quanlycauhoi.setIcon(new ImageIcon("Images/quanlycauhoi.png"));
        quanlydapan.setIcon(new ImageIcon("Images/quanlydapan.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        quanlyuser = new javax.swing.JLabel();
        quanlyluat = new javax.swing.JLabel();
        quanlybienbao = new javax.swing.JLabel();
        quanlybaithi = new javax.swing.JLabel();
        quanlycauhoi = new javax.swing.JLabel();
        quanlydapan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));
        getContentPane().add(jLabel6);

        jPanel1.setLayout(new java.awt.GridLayout(8, 1));
        jPanel1.add(jLabel5);

        quanlyuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlyuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlyuserMouseClicked(evt);
            }
        });
        jPanel1.add(quanlyuser);

        quanlyluat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlyluat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlyluatMouseClicked(evt);
            }
        });
        jPanel1.add(quanlyluat);

        quanlybienbao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlybienbao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlybienbaoMouseClicked(evt);
            }
        });
        jPanel1.add(quanlybienbao);

        quanlybaithi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlybaithi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlybaithiMouseClicked(evt);
            }
        });
        jPanel1.add(quanlybaithi);

        quanlycauhoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlycauhoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quanlycauhoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlycauhoiMouseClicked(evt);
            }
        });
        jPanel1.add(quanlycauhoi);

        quanlydapan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanlydapan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quanlydapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlydapanMouseClicked(evt);
            }
        });
        jPanel1.add(quanlydapan);

        getContentPane().add(jPanel1);
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quanlyuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlyuserMouseClicked
        QuanLyUser le = new QuanLyUser();
        le.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quanlyuserMouseClicked

    private void quanlyluatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlyluatMouseClicked
       QuanLyLuat thtrng = new QuanLyLuat();
            thtrng.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_quanlyluatMouseClicked

    private void quanlybienbaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlybienbaoMouseClicked
        QuanLyBienBao in = new QuanLyBienBao();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quanlybienbaoMouseClicked

    private void quanlybaithiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlybaithiMouseClicked
        QuanLyBaiThi in = new QuanLyBaiThi();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quanlybaithiMouseClicked

    private void quanlycauhoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlycauhoiMouseClicked
        QuanLyCauHoi n = new QuanLyCauHoi();
                n.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_quanlycauhoiMouseClicked

    private void quanlydapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlydapanMouseClicked
        QuanLyDapAn in = new QuanLyDapAn();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quanlydapanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel quanlybaithi;
    private javax.swing.JLabel quanlybienbao;
    private javax.swing.JLabel quanlycauhoi;
    private javax.swing.JLabel quanlydapan;
    private javax.swing.JLabel quanlyluat;
    private javax.swing.JLabel quanlyuser;
    // End of variables declaration//GEN-END:variables
}
